image:
  name: kalrabb/docker-swen-250-identifier-convention-chkr-img:latest
#  name: kalrabb/swen-250-project-ci:latest
#  name: kalrabb/ub_250_base:latest

variables:
  PROJECT_FOLDER: regex_md
  BUILD_CMD: make
  RUN_CMD: valgrind --leak-check=full ./md_convert -i markdown_sample.md -o index.html
  IDENT_NAME_CHKR: python3 run.py /builds/$CI_PROJECT_PATH/$PROJECT_FOLDER

before_script:
# check a few settings   - cat /etc/lsb-release
  - which gcc
  - which g++
  - which valgrind
  - which make

testrunner:
 script:
   - cd $PROJECT_FOLDER
   - $BUILD_CMD
   - $RUN_CMD
#   - cd /identifier_convention_checker
   - pwd
#   - $IDENT_NAME_CHKR

 stage: test

pages:
  stage: deploy
  script:
    - cd $PROJECT_FOLDER  #Looks like this now runs as a separate stage vs. after script, so have to go to folder
    - mkdir ../public
    - mkdir ../public/$PROJECT_FOLDER
    - cp ./index.html ../public/$PROJECT_FOLDER
    - echo "URL for converted page:"$CI_PAGES_URL/$PROJECT_FOLDER
  artifacts:
    paths:
    - public
